### ISSUE TITLE
Can we delegate search to Europe PMC?

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#141]
User story: A reader does not have a specific article DOI in mind.

Replace the DOI box with a search of Europe PMC content and display the results on a separate page.

Clicking on a result should redirect to the article page displaying title, authors, abstract.

**Comment by giorgiosironi** [comment]
Reading a bit through https://europepmc.org/RestfulWebService

**Comment by giorgiosironi** [comment]
Example: https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=malaria%20sort_date:y&format=dc

**Comment by giorgiosironi** [comment]
What's with the `<dc:date>2020-12-01</dc:date>`? Badly translated date or item created in the future? Sorting by date may lead to unexpected results.

**Comment by giorgiosironi** [comment]
Query
- all words: https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=Delayed%20specific%20IgM%20antibody%20sort_date:y&format=dc
- precise phrase: https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=%22Delayed%20specific%20IgM%20antibody%22%20sort_date:y&format=dc
Sort: just use the relevance default order rather than relying on dates, see following problem (https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=Delayed%20specific%20IgM%20antibody&format=dc)
Dates: incorrect sample dates e.g. https://europepmc.org/article/MED/32476607
Pagination: results by default limited to 25, additional requests for more.

**Comment by giorgiosironi** [comment]
Formats
- Dublin Core loses some information like author-affiliation links https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=Delayed%20specific%20IgM%20antibody&format=dc&resultType=core
- XML and JSON map onto each other (https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=covid%20sort_date:y&format=xml&resultType=core and https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=covid%20sort_date:y&format=json&resultType=core)

**Comment by giorgiosironi** [comment]
Filter for Biorxiv: https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=covid%20PUBLISHER%3A%22bioRxiv%22&format=dc&resultType=core

**Comment by giorgiosironi** [comment]
https://europepmc.org/search?query=PUBLISHER%3A%22bioRxiv%22&page=1 shows correct dates (June a couple of days ago) without the December problem.

**Comment by giorgiosironi** [comment]
Use date published rather than date received: https://europepmc.org/search?query=PUBLISHER%3A%22bioRxiv%22&page=1&sortBy=FIRST_PDATE_D%2Bdesc

**Comment by giorgiosironi** [comment]
Just in case we need it, the abstract is plain text so better source it from somewhere else: https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=%22Uncovering%20the%20hidden%20antibiotic%20potential%20of%20Cannabis%22%20sort_date:y&format=xml&resultType=core

**Comment by giorgiosironi** [comment]
Search by DOI: https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=PUBLISHER:biorxiv%2010.1101/833392%20sort_date:y&format=xml&resultType=core
