### ISSUE TITLE
Add Review Commons reviews

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#178]
Import Review Commons reviews from Hypothesis.

**Comment by giorgiosironi** [comment]
1. Is there any duplication with the eLife editorial community (reviews that appear on both sides)? According to the [Hypothesis group](https://hypothes.is/groups/NEGQVabn/review-commons) all the 111 annotations have been created by the `EMBOpress` account so no overlap.

1. I guess we are missing a name, description, logo, etc for the new editorial community page? And is it `Review Commons` or `EMBOpress`?

1. However there is also a `Reply to the reviewers`. Should that be included somehow?

1. Permalink to one review: https://hypothes.is/a/-8oO9LDGEeqx599D5Swz_Q This should probably be where the `Read more` links points to?

1. The markdown from the `text` property should be converted to HTML and truncated for the summary shown in our page?

1. The date from the `created` property will be shown, which is the date of the annotation creation on Hypothes.is, as we don't have anything more specific.

1. Should any of the articles be endorsed? Probably not.

1. At the moment we add ReviewReferences manually, what is the relevant set to add here? All of them up to the point in which we do this work? This is about [111 reviews](https://hypothes.is/groups/NEGQVabn/review-commons).

## Notes

Loaded with `curl https://api.hypothes.is/api/annotations/-8oO9LDGEeqx599D5Swz_Q | jq .`

Example of reviewed article:
https://www.biorxiv.org/content/10.1101/2020.04.17.045971v1
Has 2 reviews from EMBOpress, which appears to be in the [Review Commons Hypothesis group](https://hypothes.is/groups/NEGQVabn/review-commons)

**Comment by giorgiosironi** [comment]
1. No contention
2. `Review Commons` (eLife will not be part of this group)
3. Skip this (somehow), and push the decision of what to do with it later on outside of this ticket.
4. Yes that's the link.
5. Yes, convert to HTML and truncate
6. Yes, use `created`.
7. No. Let's worry about that later. It may even coming from another journal, and they would endorse another version of the article (that they accepted) rather than the v1 of the preprint.
8. First 10 as they appear on the [Hypothesis group as of 2020-06-24](https://hypothes.is/groups/NEGQVabn/review-commons).

**Comment by thewilkybarkid** [comment]
Bit hidden, but https://web.hypothes.is/help/formatting-annotations-with-markdown/ suggests that they use GitHub-flavoured Markdown.
