### ISSUE TITLE
Persist logs

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/prc#62]
As the app currently isn't persistent, we can only tell if someone has used the add review form through the logs. We need to persist these across deploys, and ideally somewhere that we can query easily.

**Comment by giorgiosironi** [comment]
Evaluated a `Volume` but would mean creating an EBS through the AWS API externally, which is not reproducible. Going for a `PersistentVolumeClaim` and assuming the [`PersistentVolume`](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) is created automatically by the EKS setup.

**Comment by giorgiosironi** [comment]
Added and mounted at `/var/log/app`.

Questions:
- how does the volume get handed over from one Pod to the next that gets created during deployment?
- how does the Pod get scheduled to the right node, given the nodes are in different availability zones and the PersistentVolume is local to one of them?

**Comment by giorgiosironi** [comment]
All the options:
- Local persistence of `kubectl logs` coming from stdout and stderr: this doesn't seem to be extendable to more than crashed containers in a Pod. Every deployment creates a new Pod.
- Export `kubectl logs` with a `DaemonSet`: possible in principle, but requires investment in the Libero infrastructure with unclear payoff, and adds an external service to export to.
- Volume: requires the application code/libraries to also log to a file rather than just to stdout/stderr, but shell tricks don't seem to work at least within the Alpine/Busybox-provided shell (`ash`). Also implies there's only 1 Node.js container and no replicas.

**Comment by giorgiosironi** [comment]
1. Choose an aggregator
1. Check support for `logfmt`
1. Integrate with Fluentd running as a `DaemonSet`
1. Make application write logs in this format

**Comment by giorgiosironi** [comment]
Using [AWS Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html) which is just running Fluentd as a DaemonSet with a default configuration, along with a CloudWatch agent to upload the logs of all Pods there.

Logs can be accessed through the [console](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logs-insights:queryDetail=~(end~0~start~-3600~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*0a*7c*20filter*20*60kubernetes.labels.app_kubernetes_io*2finstance*60*3d*22prc--prod*22*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2020~isLiveTail~false~queryId~'89133ab9-5bb4-4770-b3e9-96052e8300ef~source~(~'*2faws*2fcontainerinsights*2flibero-eks--franklin*2fapplication));tab=logs).

The default format is just a text line, plus other fields that are generated such as the Kubernetes labels, which help in filtering the application logs coming from all Pods that were ever deployed.
