### ISSUE TITLE
Define adequate UX for current hypothesis testing 

### ISSUE THREAD

**Issue by giorgiosironi** [libero/prc#68]
@hdrury1 @chugginselifesciences

**Comment by davidcmoulton** [comment]
**Step 0**: document the hypothesis / hypotheses under test.

Some initial thoughts for the reading experience:


- It should have a goldilocks level of design applied: if it looks too rough, that could be a barrier to engagement, but if it looks too polished, it might be seen as a commitment to doing it that way, when things are very much in flux. This is a description of an approach rather than specific UX  requirements.
- Add a list of most recent 5 items to the home page, in addition to the pre-existing editorial community links. Aim: to demonstrate rapidly changing content, and to provide a direct way to access latest content (might be more effective when we have more rapidly changing content).
- Add microcopy to document current restrictions on searching. Aim: to avoid user user frustration through searching in ways that aren't yet supported.
- Update search box placeholder text to something more meaningful. It should work with the updated microcopy, but be capable of standing alone. Aim: to provide more context for the user.

This doesn't touch on the contribution experience. Ideas to come on that in due course.

**Comment by chugginselifesciences** [comment]
I'd like to suggest only listing recent reviews on the home page and moving editorial communities to another page if realistic within time constraints. I worry that both on the homepage will confuse the purpose of the homepage.

I'm picturing a stripped back version of this page - note the "Editorial Communities" link in the top menu.

https://invis.io/B9WVPQAS4PE#/415097280_home-Logged-In

**Comment by hdrury1** [comment]
Additional thoughts on contribution experience:

- The disclaimer text surrounding the add review form should clearly establish what information is expected and set the expectation that it may not persist due to the demonstrative nature of the site. See #61 

- We should add a submit button affordance to establish a clear way for the user to add their review. See https://github.com/libero/prc/issues/79

- The placeholder text of the DOI input should be more descriptive. See https://github.com/libero/prc/issues/80

- The title of the form should be more descriptive. See https://github.com/libero/prc/issues/78

**Comment by hdrury1** [comment]
Tickets raised, with prioritised work added to To Do.
